# We don't need sudo as such, but setting sudo: required allows us to run on
# the faster machines which means that the builds complete much faster (in
# about half the time). For comparison, here are two builds on the two
# different machines:
# - With `sudo: false`: https://travis-ci.org/opbeat/opbeat-node/builds/252301998
# - With `sudo: required`: https://travis-ci.org/opbeat/opbeat-node/builds/252302576
sudo: required

language: node_js

services:
- mysql
- mongodb
- redis-server
- postgresql

node_js:
  - '0.12'

jobs:
  include:
    # Node.js 0.12
    - stage: dependencies
      node_js: '0.12'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: tav --quiet
    -
      node_js: '0.12'
      env: TAV=ioredis,pg
      script: tav --quiet
    -
      node_js: '0.12'
      env: TAV=bluebird
      script: tav --quiet
    -
      node_js: '0.12'
      env: TAV=knex,ws,graphql,express-graphql
      script: tav --quiet
